name: json_serializable
version: 2.0.0-dev
author: Dart Team <misc@dartlang.org>
description: Generates utilities to aid in serializing to/from JSON.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: '>=2.0.0-dev.65 <3.0.0'

dependencies:
  analyzer: ^0.33.0
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.4.0'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation`. Properly constrains all features it provides.
  json_annotation: '>=1.2.0 <1.3.0'
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: ^0.9.1+2

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.0
  build_verify: ^1.1.0
  build_web_compilers: ^0.4.0+1
  collection: ^1.14.0
  dart_style: ^1.0.0
  logging: ^0.11.3+1
  test: ^1.3.3
  yaml: ^2.1.13
